function getQueryStringValue(key){return decodeURIComponent(window.location.search.replace(new RegExp("^(?:.*[&\\?]"+encodeURIComponent(key).replace(/[\.\+\*]/g,"\\$&")+"(?:\\=([^&]*))?)?.*$","i"),"$1"));}
function updateUrlParameter(uri,key,value){var
i=uri.indexOf('#'),hash=i===-1?'':uri.substr(i);uri=i===-1?uri:uri.substr(0,i);var
re=new RegExp("([?&])"+key+"=.*?(&|$)","i"),separator=uri.indexOf('?')!==-1?"&":"?";if(!value){uri=uri.replace(new RegExp("([?&]?)"+key+"=[^&]*","i"),'');if(uri.slice(-1)==='?'){uri=uri.slice(0,-1);}
if(uri.indexOf('?')===-1){uri=uri.replace(/&/,'?');}}else if(uri.match(re)){uri=uri.replace(re,'$1'+key+"="+value+'$2');}else{uri=uri+separator+key+"="+value;}
return uri+hash;}
var
sourcesSelector=document.querySelectorAll('select[name=sources]'),sourcesTotal=sourcesSelector.length;for(var i=0;i<sourcesTotal;i++){sourcesSelector[i].addEventListener('change',function(){var
media=this.closest('.players').querySelector('.mejs__container').id,player=mejs.players[media];player.setSrc(this.value.replace('&amp;','&'));player.load();if(!mejs.Features.isiOS&&!mejs.Features.isAndroid){player.play();}
var renderer=document.getElementById(player.media.id+'-rendername');renderer.querySelector('.src').innerHTML='<a href="'+this.value+'" target="_blank">'+this.value+'</a>';renderer.querySelector('.renderer').innerHTML=player.media.rendererName;renderer.querySelector('.error').innerHTML='';});if(mejs.Features.isiOS){sourcesSelector[i].querySelector('option[value^="rtmp"]').disabled=true;if(sourcesSelector[i].querySelector('option[value$="webm"]')){sourcesSelector[i].querySelector('option[value$="webm"]').disabled=true;}
if(sourcesSelector[i].querySelector('option[value$=".mpd"]')){sourcesSelector[i].querySelector('option[value$=".mpd"]').disabled=true;}
if(sourcesSelector[i].querySelector('option[value$=".ogg"]')){sourcesSelector[i].querySelector('option[value$=".ogg"]').disabled=true;}
if(sourcesSelector[i].querySelector('option[value$=".flv"]')){sourcesSelector[i].querySelector('option[value*=".flv"]').disabled=true;}}}
document.addEventListener('DOMContentLoaded',function(){var mediaElements=document.querySelectorAll('audio'),i,total=mediaElements.length;for(i=0;i<total;i++){new MediaElementPlayer(mediaElements[i],{pluginPath:'../build/',success:function(media){var renderer=document.getElementById(media.id+'-rendername');media.addEventListener('loadedmetadata',function(){var src=media.originalNode.getAttribute('src').replace('&amp;','&');if(src!==null&&src!==undefined&&renderer!==null){renderer.querySelector('.src').innerHTML='<a href="'+src+'" target="_blank">'+src+'</a>';renderer.querySelector('.renderer').innerHTML=media.rendererName;renderer.querySelector('.error').innerHTML='';}});media.addEventListener('error',function(e){renderer.querySelector('.error').innerHTML='<strong>Error</strong>: '+e.message;});}});}});