$(document).ready(function(){$.ajaxSetup({cache:true});var is_load=0;function loadjs(){if(is_load==0){is_load=1;console.log('Lazy JS Start');$('script[type=lazyjs]').each(function(){var url=$(this).attr('src');if(url)$.getScript(url);else{$(this).attr('type','text/javascript');var sc=$(this).html();eval(sc);}});var lazyLoadInstanceBanner=new LazyLoad({elements_selector:"img.lazyloadbn"});}}
$(window).scroll(function(){loadjs();});$(window).mousemove(function(){loadjs();});setTimeout(function(){loadjs();},12000);var device='desktop';if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){$('.hide_mb').hide();device='mobile';}
else $('.hide_pc').hide();$('script[type='+device+'js][src]').each(function(){$(this).attr('type','text/javascript');var url=$(this).attr('src');$.getScript(url);});$('script[type='+device+'js]:not([src])').each(function(){$(this).attr('type','text/javascript');var sc=$(this).html();try{eval(sc);}catch(e){if(e instanceof SyntaxError){console.log(e.message);}}});$('.navbar-mb-header__close').on('click',function(){$('#sidebar').removeClass('active');$('.overlay').removeClass('active');});});$(document).ready(function(){const appKey="df38fffb1a6ce92a3dea15aaa7e03491";function findWeatherDetails(city="Hanoi"){let searchLink="https://api.openweathermap.org/data/2.5/weather?q="+city+"&APPID="+appKey;httpRequestAsync(searchLink,theResponse);}
function theResponse(response){let jsonObject=JSON.parse(response);var src="https://openweathermap.org/img/w/"+jsonObject.weather[0].icon+".png";$('.icon-weather').attr('src',src);$('.tempt').html(parseInt(jsonObject.main.temp-273)+"°C");$('.humidity').html(parseInt(jsonObject.main.humidity)+"%");}
function httpRequestAsync(url,callback){var httpRequest=new XMLHttpRequest();httpRequest.onreadystatechange=()=>{if(httpRequest.readyState==4&&httpRequest.status==200)
callback(httpRequest.responseText);}
httpRequest.open("GET",url,true);httpRequest.send();}
findWeatherDetails();$('#weatherLocation').change(function(){findWeatherDetails($(this).val());});$('#btn-submit-report').click(function(){var norobot=$('#mail-capt').val();var email=$('#email').val();var content=$('#content').val();var news_id=$('#news_id').val();var phone=$('#phone').val();if(!content||(!email&&!phone)){alert('Vui lòng nhập email hoặc số điện thoại của bạn để chúng tôi có thể gửi lời cảm ơn tới bạn!');}
else if(email&&!validateEmail(email)){alert('Email không hợp lệ');$('#mail-com').focus();}
else{$('.loading-process').css('display','block');$.ajax({url:'/?mod=news&act=report',type:'POST',data:{email:email,content:content,news_id:news_id,phone:phone,norobot:norobot,},success:function(html){if(html=='0'){alert('Sai captcha');return false;}
else{$('#close-report').click();setTimeout(function(){alert("Gửi thành công! Cảm ơn bạn đã quan tâm đến nongnghiep.vn");},100)}
$('.loading-process').css('display','none');}});}});now=new Date;time='';var days=['Chủ Nhật','Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy'];var day='<strong>'+days[now.getDay()]+',</strong> ';var date=now.getDate();var month=now.getMonth()+1;var year=now.getFullYear();var hour=now.getHours();var minutes=now.getMinutes();var time=time+day+date+'/'+month+'/'+year+' '+hour+':'+minutes+' (GMT +7)';$('.time').html(time);});function validateEmail(email){var re=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(email);}
function copyUrl(string=null){var aux=document.createElement("input");var str=string||window.location.href;aux.setAttribute("value",str);document.body.appendChild(aux);aux.select();document.execCommand("copy");document.body.removeChild(aux);}
function copyUrlDetail(string=null,boxAlert){copyUrl(string)
var tooltip=document.getElementById(boxAlert);tooltip.innerHTML="Đã copy";}
function outFunc(boxAlert){var tooltip=document.getElementById(boxAlert);tooltip.innerHTML="Click để copy";}
function handlHoverSource(x){handlCommont();}
function handlOutSource(x){handlCommont();}
function handlCommont(){const sourceDetail=document.querySelector(".link-source-detail");sourceDetail.classList.toggle("open-tp");}
function copyUrlSourceLink(string){copyUrl(string);const textCopy=document.querySelector(".btn-copy-link-source i");textCopy.innerHTML="Đã copy"}
window.onscroll=function(){scrollFunction()};scrollFunction();function scrollFunction(){var floading_bar=document.getElementById('floating-bar');if(floading_bar){if(document.documentElement.scrollTop>458){floading_bar.style.position="fixed";floading_bar.style.top="31vh";floading_bar.style.opacity="1";}
else{floading_bar.style.position="relative";floading_bar.style.top="0";}}}
jQuery(document).ready(function($){$("#menu").mmenu({"extensions":["fx-menu-zoom"],"counters":true});});var btn=$('#button');$(window).scroll(function(){if($(window).scrollTop()>300){btn.addClass('show');}else{btn.removeClass('show');}});btn.on('click',function(e){e.preventDefault();$('html, body').animate({scrollTop:0},'300');});$('#openMenu').click(function(){if($('.dropdown-menu').hasClass('show')){$('#closeMenu').css('display','none');$('.open-menu-icon').css('display','flex');}
else{$('#closeMenu').css('display','block');$('.open-menu-icon').css('display','none');}});$('.searh-mobile-icon').click(function(){$('.search-form-mobile').toggle().fade();});const hamburger1=document.querySelector(".show-menu-other1");const hamburger=document.querySelector(".show-menu-other");const navLinks=document.querySelector(".menu-other");const links=document.querySelectorAll(".menu-other li");hamburger.addEventListener("click",()=>{console.log(0)
navLinks.classList.toggle("open-tp");links.forEach(link=>{link.classList.toggle("fade-tp");});});hamburger1.addEventListener("click",()=>{console.log(1)
navLinks.classList.toggle("open-tp");links.forEach(link=>{link.classList.toggle("fade-tp");});});$(document).ready(function(){$("#sidebar").css("position"," fixed");});$(document).ready(function(){$('#dismiss, .overlay').on('click',function(){$('#sidebar').removeClass('active');$('.overlay').removeClass('active');});$('#sidebarCollapse').on('click',function(){$('#sidebar').addClass('active');$('.overlay').addClass('active');$('.collapse.in').toggleClass('in');$('a[aria-expanded=true]').attr('aria-expanded','false');});});$(document).ready(function(){$('#dismiss, .overlay').on('click',function(){$('#sidebar').removeClass('active');$('.overlay').removeClass('active');});$('#sidebarCollapse1').on('click',function(){$('#sidebar').addClass('active');$('.overlay').addClass('active');$('.collapse.in').toggleClass('in');$('a[aria-expanded=true]').attr('aria-expanded','false');});});var bavbarFooter=document.querySelector(".navbar-footer-tp");hamburger.addEventListener("click",()=>{let statusUtility=$('.box-tag-utility').hasClass('active');if(statusUtility)showUtility();navLinks.classList.toggle("open-tp");links.forEach(link=>{link.classList.toggle("fade-tp");});});$(document).ready(function(){$(".menu-search_btn").click(function(){let status=($(this).attr("data-status")=='true');let form=$(".search-bar");$(this).removeAttr('data-status');if(status){form.css({opacity:1,visibility:"hidden"});($(this).children('i')).remove();$(this).append("<i class='fa fa-search' aria-hidden='true'></i>");}else{form.css({opacity:1,visibility:"visible"});($(this).children('i')).remove();$(this).append("<i class='fa fa-times' aria-hidden='true'></i>");}
$(this).attr('data-status',!status);});$('#dismiss, .overlay').on('click',function(){$('#sidebar').removeClass('active');$('.overlay').removeClass('active');});$('#sidebarCollapse').on('click',function(){$('#sidebar').addClass('active');$('.overlay').addClass('active');$('.collapse.in').toggleClass('in');$('a[aria-expanded=true]').attr('aria-expanded','false');});$('#showUtility').on('click',function(){showUtility();});$("#sidebar").css("position"," fixed");});function showUtility(){$('.box-tag-utility').toggleClass('active');}
$(".Exercice .list_Exercice").change(function(){var children_id=$(".Exercice .list_Exercice").val();$.ajax({url:'/?mod=gym&act=get_Exercice',data:{children_id:children_id},error:function(){},dataType:'html',success:function(data){$(".list_Exercice_content").html(data);},type:'GET'});});function copyToClipboard(element){var $temp=$("<input>");$("body").append($temp);$temp.val($(element).data('link')).select();document.execCommand("copy");$temp.remove();}
$('.copy-link').click(function(){$('#copySuccess').show().delay(500).fadeOut();;});$('#keyword_item').keyup(function(e){var str=$('#keyword_item').val().trim();var str=str.replace(' ','+');var url="https://homeaz.vn/toan-quoc/mua-ban/?order_by=0&q="+str;$("#f_sm_search").attr("action",url);if(e.keyCode==13){location.href=url;}});$('#load_mobile').on('click',onLoad);function onLoad(){page++;$.ajax({url:"?mod=news&act=loadmore_topic",method:'get',data:{'category_id':category_id,'page':page,'v':d.getSeconds()},context:$('.append_dataload'),}).done(function(data){$(this).append(data);});}
$(document).ready(function(){$('.you_video').each(function(){var w=$(this).width();$(this).css('height',(w*9/16)+'px');});var width_content=$('#content_detail').width();var src,width,height;$('figure').each(function(){width=$(this).find('img').attr('width');height=$(this).find('img').attr('height');if(isNaN(width)||width==undefined||width==0||isNaN(height)||height==undefined){}
else{var max_height=parseInt(width_content*height/width);width=Math.min(width,width_content);height=Math.min(height,max_height);src=$(this).find('img').attr('data-src');if(src==undefined)src=$(this).find('img').attr('src');$(this).find('figcaption').width(width-6);}
var caption=$(this).find('figcaption h2').html();if(caption=='&nbsp;'||caption==' ')$(this).find('figcaption').remove();});$('.exp_tinyslide').each(function(){var count_item=$(this).find('figure').size();var html='';if(count_item==1){$(this).find('img').each(function(){html+='<figure><img src="'+$(this).attr('src')+'" alt="'+$(this).attr('alt')+'"><figcaption><h2>'+$(this).attr('alt')+'</h2></figcaption></figure>';});}
else if(count_item==2){html='<div class="exp_slide_two js">';$(this).find('img').each(function(){html+='<img src="'+$(this).attr('src')+'" alt="'+$(this).attr('alt')+'" />';});html+='</div>';}
else{html='<div class="explus_slider"><span class="btn_left"></span><span class="btn_right"></span><div class="slider-for">';$(this).find('.exp_wrap').children().each(function(){if($(this).hasClass('exp_video'))html+='<div><iframe class="exp_video" src="'+$(this).attr('src')+'?demo" width="100%" height="100%" frameborder="0" allowfullscreen="true"></iframe></div>';else html+='<div>'+$(this).html()+'</div>';});html+='</div></div>';}
$(this).html(html).show();});if($('.exp_area_vote').length>0){var s=document.createElement('script');s.type='text/javascript';s.src='/lib/vote/script.js?v=1';$('head').append(s);}
if($('.exp_qc_share').length>0){$('.exp_qc_share').each(function(){var id=$(this).attr('data-id');var total=$(this).find('.exp_qc_one').size();var qc=parseInt($.cookie('QC_SHARE_'+id));if(!qc)qc=1;qc++;if(qc>total)qc=1;$.cookie("QC_SHARE_"+id,qc);$(this).find('.exp_qc_one:eq('+(qc-1)+')').addClass('active');var sleep=parseInt($(this).attr('data-sleep'));var obj=$(this);if(sleep){setInterval(function(){qc++;if(qc>total)qc=1;$.cookie("QC_SHARE_"+id,qc);obj.find('.active').removeClass('active');obj.find('.exp_qc_one:eq('+(qc-1)+')').addClass('active');},(sleep*1000));}});}
if($('.live_info').length>0){var i=parseInt($('.live_info').find('b').text());var mask=i;var news_id=parseInt($('.live_info').find('b').attr('data-id'));setInterval(function(){i--;if(i>0)$('.live_info b').text(i);else if(i==0){$.ajax({type:"GET",url:"/live_content/"+news_id,dataType:"html",success:function(msg){$('.exp_tbllive').html(msg);i=mask;}});}},1000);}
if($('#gotolink').length>0)window.location.href=$('#gotolink').text();});(function($){$(function(){$.getJSON('https://content.googleapis.com/youtube/v3/channels?id=UC4ggb9_Avn-elvuEVsJYr2Q&key=AIzaSyCzc3d1NVHyoaxxB1QYoI2_ctQPG93NhQw&part=statistics',function(response){if(response.items.length>0){$('.box_footer1_text1 .counter').text(new Number(response.items[0].statistics.subscriberCount).toLocaleString());}});});})(jQuery);